### ISSUE TITLE
Can you provide a manual about the detailed commands setting of global.json?

### ISSUE THREAD

**Issue by 919607** [deepmodeling/APEX#3]
The currently provided examples are all based on the bohrium platform. When migrating to a personal server, the setting of global.json may be inaccurate and cause it to fail to run normally.

**Comment by ZLI-afk** [comment]
We are currently working on the more detailed manual on APEX. You may refer to [DPDispatcher’s documentation](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/) style of setting for dispatch jobs on a local or HPC like environment. Notice that you will need to include information of machine, resources, and task as nested dictionary in the global.json so that the APEX can recognize them properly.

**Comment by ZLI-afk** [comment]
> The currently provided examples are all based on the bohrium platform. When migrating to a personal server, the setting of global.json may be inaccurate and cause it to fail to run normally.

We are currently working on the more detailed manual on APEX. You may refer to [DPDispatcher’s documentation](https://docs.deepmodeling.com/projects/dpdispatcher/en/latest/) style of setting for dispatch jobs on a local or HPC like environment. Notice that you will need to include information of machine, resources, and task as nested dictionary in the global.json so that the APEX can recognize them properly.
